### ISSUE TITLE
Create a FUSE driver

### ISSUE THREAD

**Issue by IanSeyler** [ReturnInfinity/BMFS#13]
http://fuse.sourceforge.net/

**Comment by tholberton** [comment]
I'd like to start this.

Should the fuse driver be separate bmfs program (like bmfs-fuse)? This would require sharing some code between bmfs.c and bmfs-fuse.c (like in bmfs-lib.c). I would like this because it would make it easier to support other FUSE-like libraries (like [dokany](https://github.com/dokan-dev/dokany), a FUSE equivalent for Windows).

On the other hand, replacing or merging the original bmfs.c interface with the fuse interface may get done with less work.

**Comment by tay10r** [comment]
Well almost a year later and I finally decided to write some code for this!

I created a branch on my fork called `fuse-support`. There you'll find the `bmfs-fuse` program, which currently supports reading files. While it does not yet support creating, deleting or writing files, it does demonstrate the proof-of-concept.

You can see it work by doing:
```
touch disk.image
./bmfs disk.image format
./bmfs disk.image create README.md
./bmfs disk.image write README.md
mkdir mnt
./bmfs-fuse mnt
ls mnt
cat mnt/README.md
```
I'm going to finish implementing the file system functions and create the pull request.

**Comment by tay10r** [comment]
All done! See PR #18
