### ISSUE TITLE
Recovery Tool

### ISSUE THREAD

**Issue by ghost** [ReturnInfinity/BMFS#32]
In the event that a file is deleted, there should be a tool that makes some attempt at recovering it.

This can be done by traversing the directory and checking for the best matches with files that have been marked deleted.

**Comment by tay10r** [comment]
This is still possible after v2.0.0, but it will have to be done differently. Deleted entries in the allocation table can be marked as deleted, instead of zeroed out, so that they can be searched later. This can also be done with entries. New allocation will prefer regions that have not been deleted, until there is no space left except the deleted regions.
