### ISSUE TITLE
Any support to work within a partition, or have BMFS allow partitions, including hidden or duress partition?

### ISSUE THREAD

**Issue by dd6905** [ReturnInfinity/BMFS#44]

**Comment by tay10r** [comment]
The BMFS utility will ignore partition structures on a disk file. I think the closest we can come to properly handling a partitioned disk file is by allowing the specification of the starting offset and size of the partition in the command line. Would this suite your needs?

Most file system utilities that I've seen don't seem to treat partitioned files. In Linux, this is mostly inconsequential since partitions can be treated as separate files by the virtual file system. On Windows, not quite sure how it's approached.

**Comment by dd6905** [comment]
It would have to be for former where BMFS where BMFS can handle partitions since I believe it is being marketed as a full disk system. But BMFS should be able to be a partition within say a GPT partition if one would like to subdivide a disk. Since BMFS is a "full disk" idea, then not recognizing existing parition tables looses other vital features such as being able to Online Grow a disk, or trying to preserve existing persistent data on the disk without having BMFS blow it away. But also an official GPT and/or fdisk partiton type is needed so if the BMFS is referred to by a partition reference eg /dev/sda1. /dev/sda partition table needs to recognize the /dev/sda1 in it's partition tables. I assume there is no Partition Type allocated for bmfs

**Comment by tay10r** [comment]
No, you don't need to recognize partition formats in file system programs. Every sane partitioning tool can give you the offset and size of a partition, because that's what's usually used to make a file system program work on a specific partition. 

Granted, that's not currently implemented here. I'd be willing to add a disk offset and size parameter but nothing else.
